name: pleatsanddarts
favicon: null
layout_spectrum: 0.74536
typography_spectrum: 0.38048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd4280'
    - '#3c2961'
    - '#d8d994'
    - '#5f506e'
    - '#7e7c4c'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
