name: pleatsanddarts
favicon: null
layout_spectrum: 0.4109383400063962
typography_spectrum: 0.1680197597015649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2440257021225989
  lightness: 0.997894317144528
  saturation: 0.5903325411491096
  rhythmicContrast: 0.4154416637029499
purpose: []
